name: nft-marketplace-go-service
services:


  go-service:
    build: .
    image: nft-marketplace-go-service:1.0.0
    container_name: nft-marketplace-go-service-app
    restart: unless-stopped
    ports:
      - "8083:8083"
    env_file:
      - nft-marketplace.env
    environment:
      APP_PORT: "8083"
      DB_HOST: "host.docker.internal"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASS: ${DB_PASS}
      DB_NAME: "NFT_MARKETPLACE"
      DB_SSLMODE: "disable"
      APP_CHAIN_ID: ${APP_CHAIN_ID}
      APP_RPC_URL: ${APP_RPC_URL}
      APP_REWARD_VAULT_ADDRESS: ${APP_REWARD_VAULT_ADDRESS}
      APP_PLATFORM_FEE_BPS: ${APP_PLATFORM_FEE_BPS}
      APP_GOD_MODE_WALLET_ADDRESS: ${APP_GOD_MODE_WALLET_ADDRESS}
      APP_PLATFORM_TREASURY_ADDRESS: ${APP_PLATFORM_TREASURY_ADDRESS}
      APP_PLATFORM_OPERATOR_PRIVATE_KEY: ${APP_PLATFORM_OPERATOR_PRIVATE_KEY}
